name: hlebberi_sotrydn
description: A new Flutter project.
publish_to: 'none'

version: 1.0.12+12

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  table_calendar: ^3.1.2

  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.3.2
  jiffy: ^6.3.1
  carousel_slider: ^5.0.0
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  redux_thunk: ^0.4.0
  url_launcher: ^6.3.1
  flutter_color: ^2.1.0
  qr_code_scanner: ^1.0.1
  skeletonizer: ^1.4.2
  photo_view: ^0.15.0
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  image_cropper: ^8.0.2
  notifications: ^3.0.0
  dio: ^5.7.0
  flutter_dotenv: ^5.1.0
  webview_flutter_plus: ^0.4.7
  audioplayers: ^6.1.0
  webview_flutter: ^4.9.0
  permission_handler: ^11.3.1
  video_player: ^2.9.2
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/videos/