name: hlebberi_sotrydn
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  table_calendar: ^3.0.9

  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  jiffy: ^6.2.1
  carousel_slider: ^4.2.1
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  redux_thunk: ^0.4.0
  url_launcher: ^6.2.5
  flutter_color: ^2.1.0
  qr_code_scanner: ^1.0.1
  skeletonizer: ^0.8.0
  photo_view: ^0.14.0
  image_picker: ^1.0.7
  flutter_image_compress: ^2.1.0
  image_cropper: ^5.0.1
  notifications: ^3.0.0
  dio: ^5.4.1
  flutter_dotenv: ^5.1.0
  webview_flutter_plus: ^0.2.4
  audioplayers: ^5.2.1
  webview_flutter: ^2.8.0
  permission_handler: ^11.3.0
  flutter_sound: ^9.2.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/